/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class petpictureguiswing extends javax.swing.JFrame {

    /**
     * Creates new form petpictureguiswing
     */
    public petpictureguiswing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        birdbutton = new javax.swing.JRadioButton();
        catbutton = new javax.swing.JRadioButton();
        dogbutton = new javax.swing.JRadioButton();
        rabbitbutton = new javax.swing.JRadioButton();
        pigbutton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(birdbutton);
        birdbutton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        birdbutton.setText("bird");
        birdbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birdbuttonActionPerformed(evt);
            }
        });

        buttonGroup1.add(catbutton);
        catbutton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        catbutton.setText("cat");
        catbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catbuttonActionPerformed(evt);
            }
        });

        buttonGroup1.add(dogbutton);
        dogbutton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        dogbutton.setText("dog");
        dogbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dogbuttonActionPerformed(evt);
            }
        });

        buttonGroup1.add(rabbitbutton);
        rabbitbutton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        rabbitbutton.setText("rabbit");
        rabbitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rabbitbuttonActionPerformed(evt);
            }
        });

        buttonGroup1.add(pigbutton);
        pigbutton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        pigbutton.setText("pig");
        pigbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pigbuttonActionPerformed(evt);
            }
        });

        jLabel1.setText("picture");
        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pigbutton)
                    .addComponent(birdbutton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(catbutton)
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rabbitbutton)
                    .addComponent(dogbutton))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(birdbutton)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(catbutton)
                        .addGap(47, 47, 47)
                        .addComponent(dogbutton)
                        .addGap(34, 34, 34)
                        .addComponent(rabbitbutton))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addComponent(pigbutton)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void birdbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birdbuttonActionPerformed
         petLabel.setText("Pet: Bird");
    petImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("C:\\Users\\user\\OneDrive\\Documents\\NetBeansProjects\\petpicture\\src\\images\\pets\\bird.jpg"))); //TODO add your handling code here:
    }//GEN-LAST:event_birdbuttonActionPerformed

    private void catbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catbuttonActionPerformed
   petLabel.setText("Pet: Cat");
    petImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("C:\\Users\\user\\OneDrive\\Documents\\NetBeansProjects\\petpicture\\src\\images\\pets\\cat.jfif"))) ;     // TODO add your handling code here:
    }//GEN-LAST:event_catbuttonActionPerformed

    private void dogbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dogbuttonActionPerformed
    petLabel.setText("Pet: Dog");
    petImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("C:\\Users\\user\\OneDrive\\Documents\\NetBeansProjects\\petpicture\\src\\images\\pets\\dog.jpg")));     // TODO add your handling code here:
    }//GEN-LAST:event_dogbuttonActionPerformed

    private void rabbitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rabbitbuttonActionPerformed
    petLabel.setText("Pet: Rabbit");
    petImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("C:\\Users\\user\\OneDrive\\Documents\\NetBeansProjects\\petpicture\\src\\images\\pets\\rabbit.jfif")));     // TODO add your handling code here:
    }//GEN-LAST:event_rabbitbuttonActionPerformed

    private void pigbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pigbuttonActionPerformed
        petLabel.setText("Pet: Pig");
    petImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("C:\\Users\\user\\OneDrive\\Documents\\NetBeansProjects\\petpicture\\src\\images\\pets\\pig.jpg")));//TODO add your handling code here:
    }//GEN-LAST:event_pigbuttonActionPerformed

    private void jLabel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1AncestorAdded
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(petpictureguiswing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(petpictureguiswing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(petpictureguiswing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(petpictureguiswing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new petpictureguiswing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton birdbutton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton catbutton;
    private javax.swing.JRadioButton dogbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton pigbutton;
    private javax.swing.JRadioButton rabbitbutton;
    // End of variables declaration//GEN-END:variables
}
